# Agda-Material

https://pdmosses.github.io/agda-material/

# Generate websites with highlighted, hyperlinked web pages from Agda code

# Peter Mosses (@pdmosses)

##############################################################################
# MAIN TARGETS

# N.B. With GNU Make, `make ...` uses `GNUMakefile` as the default.
# Run `make -f Makefile ...` instead of `make ...` to use this `Makefile`.

# HELP
#
# make help 

# CHECK THE AGDA CODE
#
# make check

# GENERATE AND BROWSE A WEBSITE
#
# make web  
# make serve

# DEPLOY AN UNVERSIONED WEBSITE
#
# make deploy

# REMOVE GENERATED FILES
#
# make clean-all

# MANAGE VERSIONED DEPLOYMENT
#
# N.B. Before using `make start-versioning`, uncomment the following lines
# in mkdocs.yml:
#
# extra:
#   version:
#     provider: mike
#
# The `mike` commands documented at https://github.com/jimporter/mike/ provide
# more general version management possibilities than this Makefile. See also:
# https://blog.lx862.com/blog/2025-06-10-versioning-with-material-mkdocs/
#
# make start-versioning
# make deploy  VERSION=...
# make default VERSION=...
# make delete  VERSION=...
# make list-versions

##############################################################################
# ARGUMENTS
#
# Name    Purpose
# -----------------------------
# DIR     Agda import include-path(s)
# ROOT    Agda root module(s)
# HTML    generated directory for HTML files
# MD      generated directory for Markdown files

# HTML-INDEX  $(HTML-INDEX).html used for index.html page when HTML = docs
# MD-INDEX    $(MD-INDEX).md     used for index.md   page when MD = docs

# SITE    generated website
# TEMP    temporary directory
# VERSION used for managing versioned websites

# ARGUMENT DEFAULT VALUES

DIR  := agda
ROOT := Background,Examples,Tests

# Both DIR and ROOT may be comma-separated lists.
# The top level of the ROOT module(s) should be located in DIR.

HTML := docs/html
MD   := docs

# N.B. The variables HTML and MD affect the URLs of the generated pages.
# With the above defaults, the URLs of pages in the HTML section of a
# generated website are prefixed by `html/`, and the URLS of the other
# generated pages are prefixed by `md/`. It is possible to eliminate those
# prefixes by setting both variables to `docs`. However, the generation of
# pages directly in `docs` may then overwrite non-generated files (depending
# on the names of the Agda modules loaded by ROOT).

HTML-INDEX := index
MD-INDEX   := index # unused

# If ROOT = index and HTML = docs, the generated page at docs/index.html
# overrides the website home page (automatically rendered by MkDocs from
# docs/index.md or docs/README.md), and interferes with versioning.
# Set HTML-INDEX to a name that is different from all imported module names  
# to generate the page at docs/$(HTML-INDEX).html and avoid these issues;
# similarly for MD-INDEX when MD = docs.

SITE := site
TEMP := temp

# VERSION := ???
#
# The variable VERSION is an optional command argument.
# If it is set in this file, unversioned deployment is *not* supported.

# All files in the docs directory are rendered in the generated website
# (except for docs/.* files and files explicitly excluded in mkdocs.yml).
# Setting HTML to a directory *not* in docs suppresses the inclusion of
# the plain HTML pages generated by the target `gen-html` in the website.
# The target `gen-md` generates a website without generating the HTML pages.

# Top-level navigation links should be specified in docs/.nav.yml. Levels
# specified using `*` are automatically generated from the directory hierarchy
# of the Agda modules. The format of docs/.nav.yml is explained in the
# Awesome-Nav documentation (https://lukasgeiter.github.io/mkdocs-awesome-nav/).

# N.B. docs/.nav.yml is *not* automatically updated when the settings of
# ROOT, HTML, and MD are changed. When serving or deploying the generated
# website, MkDocs reports any broken navigation links in docs/.nav.yml,
# and any generated pages that are not accessible via the navigation.

# The default docs and site directories can be changed in mkdocs.yml,
# see https://www.mkdocs.org/user-guide/configuration/#build-directories

##############################################################################
# CONTENTS
#
# VARIABLES
# HELP
# CHECK THE AGDA CODE
# GENERATE AND BROWSE A WEBSITE
# DEPLOY AN UNVERSIONED WEBSITE
# REMOVE GENERATED FILES
# MANAGE VERSIONED DEPLOYMENT
# DEBUG

##############################################################################
# VARIABLES

# Characters:

EMPTY :=

SPACE := $(EMPTY) $(EMPTY)

COMMA := ,

# Shell commands:

SHELL := /bin/sh

PROJECT := $(shell pwd)

# Note: In shell commands, `$(...)` refers to a Makefile variable definition,
# and `$${...}` refers to a shell variable definition. Make removes newlines
# in shell scripts, so end-of-line shell comments `# ...` cannot be used;
# comments are written instead as dummy assignments of the form `_='# ...';`.

# Set HIDE-INDEXES to true when mkdocs.yml includes the navigation.indexes feature:

HIDE-INDEXES := $(shell grep -q '^[ \t]*- navigation\.indexes' mkdocs.yml \
			&& echo true || echo false )

# Relative paths to docs:

HTML2DOCS := $(shell echo $(patsubst docs/%,%,$(HTML)/) | sd '[^/]*/' '../')
MD2DOCS   := $(shell echo $(patsubst docs/%,%,$(MD)/)   | sd '[^/]*/' '../')

# Relative paths from docs:

DOCS2HTML := $(patsubst docs/%,%,$(HTML)/)
DOCS2MD   := $(patsubst docs/%,%,$(MD)/)

# Determine the path(s) for agda to search for imports:

INCLUDE-PATHS := $(subst $(COMMA),$(SPACE), $(DIR))

# Determine the root module path(s) and file(s):

ROOT-PATHS := $(subst .,/, $(subst $(COMMA),$(SPACE), $(ROOT)))

ROOT-FILES := \
	$(filter %.agda %.lagda %.lagda.tex %.lagda.md, \
	  $(foreach d, $(INCLUDE-PATHS), \
	    $(wildcard \
	      $(addsuffix .*, $(addprefix $d/, $(ROOT-PATHS))))))

# agda requires each include-path to be a separate option:

AGDA := agda $(addprefix --include-path=, $(INCLUDE-PATHS))
# When generating a website for a library, adding --no-default-libraries
# is recommended.

# AGDA-QUIET does not print any messages about checking modules:

AGDA-QUIET   := $(AGDA) --trace-imports=0

# AGDA-VERBOSE reports loading all modules, and the location of any error:

AGDA-VERBOSE := $(AGDA) --trace-imports=3

# Force sequential execution of phony prerequisites:

.NOTPARALLEL:

##############################################################################
# HELP

# `make` without a target is equivalent to `make help`. It lists the main
# targets and their purposes:

.PHONY: help
export HELP
help:
	@echo "$$HELP"

define HELP

make (or make help)
  Display this list of make targets
make check
  Check the Agda source files $(ROOT-FILES)

make web
  Generate a website from the Agda files
make serve
  Browse the generated website using a local server
make deploy
  Deploy an UNVERSIONED website on GitHub Pages 
make clean-all
  Remove all generated files

make start-versioning
  Clear any deployed unversioned website
make deploy VERSION=V
  Deploy version V of the generated website on GitHub Pages
make default VERSION=V
  Set version V as the default version and as the alias `default`
make delete VERSION=V
  Remove deployed version V from GitHub Pages
make list-versions
  Display a list of all deployed versions

endef

##############################################################################
# CHECK THE AGDA CODE

# `check` first tries to load all the ROOT-FILES quietly. When each root file
# has been loaded without errors, it reports that it has been checked; if an
# error occured, it reloads that file verbosely, displaying the error and its
# location (eliding the PROJECT part of the path) then exits.

.PHONY: check
check: 
	@for file in $(ROOT-FILES); do \
	  { $(AGDA-QUIET) $${file} 2>&1 > /dev/null && \
	    echo "Checked $${file}"; } || \
	  { $(AGDA-VERBOSE) $${file} 2>&1 | sed -e 's#$(PROJECT)/##'; \
	    echo "Abandoned checking $${file}"; \
	    exit; } \
	  done
	
##############################################################################
# GENERATE AND BROWSE A WEBSITE

# GENERATE A WEBSITE

# `web` generates both plain HTML pages and Markdown pages:

.PHONY: web
web: gen-html gen-md

# Generate HTML files in the HTML directory:

.PHONY: gen-html
gen-html: clean-html
#
	@rm -rf $(TEMP)
	@mkdir -p $(HTML)
#	Assumption: Loading the ROOT-FILES does not report errors.
	@for rootfile in $(ROOT-FILES); do \
	    $(AGDA-QUIET) --html --highlight-occurrences \
	        --html-dir=$(TEMP) $${rootfile}; \
	done
# 	(Agda may generate the same HTML file from more than one root file.)
# 	The inclusion of highlight-occurrences is non-standard. (If needed,
# 	it could be made customisable by defining it as a variable.)
#
ifneq ($(filter docs docs/%,$(HTML)),)
#
# 	Provided that the HTML pages are included in the generated website
#	(determined by $(HTML) not matching `docs`, nor starting with `docs/`),
# 	replace the `href` of each module definition (which is the relative URL
#	of the HTML page itself) by the URL of the corresponding MD page, and
#	add 'Definition` to the `class`.
# 	
#	When f = docs/index.html, move f to docs/$(HTML-INDEX).html.
#
	@for file in $(TEMP)/*.html; do \
	    \
	    _='# Get the path of the file relative to TEMP:'; \
	    path=$${file#$(TEMP)/}; \
	    _='# Get the module name by dropping the path extension:'; \
	    module=$${path%.*}; \
	    _='# Get modulepath by replacing `.`s with `/`s:'; \
	    modulepath=$${module//\./\/}; \
	    \
	    if   [ "$${module}" == "index" ] && [ "$(MD-INDEX)" == "index" ] && \
		 [ "$(HTML)" == "$(MD)" ]; then \
		page2html="."; \
	    else \
		page2html=""; \
	    fi; \
	    \
	    if   [ "$${module}" == "index" ] && [ "$(MD-INDEX)" == "index" ]; then \
		relurl=""; \
	    elif [ "$${module}" == "index" ] && [ "$(MD-INDEX)" != "index" ]; then \
		relurl=$(MD-INDEX)/; \
	    else \
		relurl=$${modulepath%\/index}/; \
	    fi; \
	    _='# Replace the href and class in the (unique) anchor for the module name:'; \
	    sd "<a id=\"([^\"]+)\" href=\"$${module}.html\" class=\"Module\">" \
	       "<a id=\"$$1\" href=\"$${page2html}$(HTML2DOCS)$(DOCS2MD)$${relurl}\" class=\"Module Definition\">" \
	       $${file}; \
	    _='# Move the file from TEMP to HTML:'; \
	    if [ "$${module}" == "index" ]; then \
		_='# Avoid clash with existing index.html file:'; \
	        mv -f $${file} $(HTML)/$(HTML-INDEX).html; \
	    else \
	        mv -f $${file} $(HTML)/$${module}.html; \
	    fi; \
	    \
	done
# 	Append CSS for emphasising module definitions to Agda.css:
	@printf "\n%s" "/* Generated by Agda-Material: */" \
	    >> $(TEMP)/Agda.css
	@printf "\n%s {\n  %s\n  %s\n}" ".Agda a.Module.Definition" \
		"text-decoration: underline;" \
		"font-weight: bold;" \
	    >> $(TEMP)/Agda.css
	@mv -f $(TEMP)/Agda.css $(TEMP)/highlight-hover.js $(HTML)
# 	Report the location of the generated HTML pages:
	@echo "Generated HTML pages in $(HTML)"
#
endif

# Generate Markdown files in the MD directory:

# `agda --html --html-highlight=code ROOT` generates files with highlighted
# HTML from plain and literate Agda source files. The generated file extension
# depends on the source file extension. It is:
#   - .html for .agda files,
#   - .tex  for .lagda and .lagda.tex files, and
#   - .md.  for .lagda.md files.
# (This version of Agda-Material does not generate web pages from other kinds
# of files generated by agda.)

# Some slight differences between the .tex and .md files: in the .md files,
#   - <pre> tags are followed by newlines;
#   - newlines following </pre> tags are discarded; and
#   - empty code blocks are discarded.

# The files generated by agda are transformed to Markdown pages as follows:
#   - .html: wrap the whole file in <pre class="Agda">...</pre> tags.
#   - .tex:  move the pre tags from code blocks to wrap the whole file.
#   - .md:   leave the pre tags around code blocks unchanged.
#   - .*:    wrap code blocks in <code class="Agda">...</code> tags.

# The files are generated in a fresh TEMP directory. To produce the intended
# navigation, the file generated for module M1. ... .Mn in TEMP needs to be
# renamed to MD/M1/.../Mn/index.md or MD/M1/.../Mn.md, depending on whether
# the navigation.sections feature is enabled, resp. disabled, in mkdocs.yml.
# Assumption: For all M, module M and module M.index do not both exist
# (because the generated pages would have the same URL .../M/).
#
# The links in the HTML files generated by agda --html assume they are all in
# the same directory, and that all files have extension html.
# Adjusting the links to hierarchical links with directory URLs involves:
#   - replacing the dots in the basenames of the files by slashes,
#   - prefixing the href URL by the path to the top of the hierarchy,
#   - appending a slash to the file path, and
#   - removing /index.md from URLs.
# When HTML is included in docs, the module name definitions in MD and HTML are
# hyperlinked.
# N.B. All URLs that do not include a colon are assumed to be links to modules,
# and get replaced by directory URLs (also in literate agda prose blocks).

gen-md: clean-md
#
	@rm -rf $(TEMP)
#	Assumption: Loading the ROOT-FILES does not report errors.
	@for file in $(ROOT-FILES); do \
	    $(AGDA-QUIET) --html --html-highlight=code --highlight-occurrences \
	        --html-dir=$(TEMP) $${file}; \
	done	      
# 	(The same HTML file may be generated by more than one root file.)
# 	The inclusion of highlight-occurrences is non-standard. (If needed,
# 	it could be made customisable by defining it as a variable.)
	@rm -f $(TEMP)/*.css $(TEMP)/*.js
	@mkdir -p $(MD)
#
	@filelist=$$(ls -1 $(TEMP)/*); \
	for file in $${filelist}; do \
	    \
	    _='# Get the path of the file relative to TEMP:'; \
	    path=$${file#$(TEMP)/}; \
	    _='# Get the module name by dropping the path extension:'; \
	    module=$${path%.*}; \
	    _='# Get the module title by dropping all prefixes:'; \
	    title=$${module##*.}; \
	    \
	    _='# Adjust the pre and code tags:'; \
	    case $${file} in \
	    *.html) \
		_='# Wrap the file in pre and code tags:'; \
		sd '\A' '<pre class="Agda"><code class="Agda">' $${file}; \
		sd '\z' '</code></pre>' $${file}; \
		;; \
	    *.tex) \
		_='# Replace pre tags by code tags, adjusting layout:'; \
		sd '^[ \t]*<pre class="Agda">\n([ \t]*)</pre>\n' '<code class="Agda">$$1</code>' $${file}; \
		sd '^[ \t]*<pre class="Agda">\n' '<code class="Agda">' $${file}; \
		sd '\n[ \t]*</pre>\n' '\n</code>' $${file}; \
		sd '\n[ \t]*</pre>$$' '\n</code>' $${file}; \
		_='# Wrap the file in pre tags:'; \
		sd '\A' '<pre class="Agda">' $${file}; \
		sd '\z' '</pre>' $${file}; \
		;; \
	    *.md) \
		_='# Replace pre tags by code tags:'; \
		sd '(<pre class="Agda">)' '$$1<code class="Agda">' $${file}; \
		sd '(</pre>)' '</code>$$1\n' $${file}; \
		_='# Remove --"hide" and --"/hide":'; \
		sd '<a id="[^"]*" class="Comment">--&quot;hide&quot;</a>\n' "" $${file}; \
		sd '<a id="[^"]*" class="Comment">--&quot;/hide&quot;</a>\n' "" $${file}; \
		_='# Remove @latex..@/latex:'; \
		sd '@latex[^@]*@/latex' '' $${file}; \
		_='# Ensure the page starts with a heading:'; \
		line=$$(head -n 1 $${file}); \
		if [ "$${line#\#}" = "$${line}" ]; then \
		    sd '\A' "# $${title}\n\n" $${file}; \
		fi; \
		;; \
	    *) \
		echo "Module $${module} has an unsupported type of literate Agda."; \
		echo "Agda-Material did not generate a web page for it,"; \
		echo "and all references to the module are broken links."; \
		exit; \
		;; \
	    esac; \
	    \
	    _='# Prepend front matter:'; \
	    if [ "$${file##*.}" == "md" ]; then \
		sd -- '\A' "---\ntitle: $${title}\n---\n\n" $${file}; \
	    else \
		sd -- '\A' "---\ntitle: $${title}\nhide: toc\n---\n\n" $${file}; \
	    fi; \
	    \
	    _='# Replace local urls to html files in hrefs by directory urls:'; \
	    sd '(href="[^:"]+)\.html' '$$1/' $${file}; \
	    _='# Replace flat local urls in hrefs by hierarchical urls:'; \
	    while grep -q 'href="[^:".][^:".]*\.' $${file}; do \
		sd '(href="[^:".][^:".]*)\.' '$$1/' $${file}; \
	    done; \
	    _='# Replace `...index/` by `...` in local urls:'; \
	    sd '(href="[^:"]*)index/' '$$1' $${file}; \
	    \
	    _='# Get modulepath by replacing `.`s with `/`s:'; \
	    modulepath=$${module//\./\/}; \
	    \
	    if   [ "$${module}" == "index" ] && [ "$(MD-INDEX)" == "index" ]; then \
		mdpage=index.md; \
		relurl=""; \
	    elif [ "$${module}" == "index" ] && [ "$(MD-INDEX)" != "index" ]; then \
		mdpage=$(MD-INDEX).md; \
		relurl=$(MD-INDEX)/; \
	    elif $(HIDE-INDEXES) && \
		 [ "$${title}" != "index" ] && \
		 (echo "$${filelist}" | grep -q "$(TEMP)/$${module}\.[^.]*\.[^.]*"); \
	    then \
		_='# Non-leaf modules become index pages:'; \
		mdpage=$${modulepath}/index.md; \
		relurl=$${modulepath}/; \
	    else \
		mdpage=$${modulepath}.md; \
		_='# Index pages:'; \
		relurl=$${modulepath%\/index}/; \
	    fi; \
	    \
	    _='# Get the relative path to MD:'; \
	    path2md=$$(echo $${relurl} | sd '[^/]*/' '../'); \
	    _='# Prefix local urls by the relative path to MD:'; \
	    sd "href=\"([^:\"]*)\"" "href=\"$${path2md}\$$1\"" $${file}; \
	    \
	    _='# If the HTML pages are included in the generated website:'; \
	    if [ -z "$(DOCS2HTML)" ] || [ "$(DOCS2HTML)" != $(HTML)/ ]; then \
		_='# Get the name of the HTML page for the module:'; \
		if [ "$${module}" == "index" ]; then \
		    htmlmodule=$(HTML-INDEX); \
		    mdurl=""; \
		else \
		    htmlmodule=$${module}; \
		    mdurl=$${relurl}; \
		fi; \
		_='# Replace the href and class in the (unique) anchor for the module name:'; \
		sd "<a id=\"([^\"]+)\" href=\"$${path2md}$${mdurl}\" class=\"Module\">" \
		   "<a id=\"$$1\" href=\"$${path2md}$(MD2DOCS)$(DOCS2HTML)$${htmlmodule}.html\" class=\"Module Definition\">" \
		   $${file}; \
	    fi; \
	    \
	    _='# Ensure the directory for the page exists:'; \
	    mkdir -p $$(dirname $(MD)/$${mdpage});  \
	    _='# Move the file from TEMP to MD:'; \
	    mv -f $${file} $(MD)/$${mdpage}; \
	    \
	done
# 	Report the location of the generated MD pages:
	@echo "Generated MD pages in $(MD)"

# The links generated by Agda always start with the file name. This could be
# removed for local links where the target is in the same file. Similarly, the
# links to modules in the same directory could be optimized.

# As with the generation of HTML files in the HTML directory, it is left to
# the user to identify and delete outdated `*.md` files manually when MD=docs.

# BROWSE THE GENERATED WEBSITE

# `make serve` provides a local preview of a generated website (ignoring any
# deployed versions).

.PHONY: serve
serve:
	@NO_MKDOCS_2_WARNING=1 mkdocs serve --livereload --dev-addr localhost:8001

##############################################################################
# DEPLOY AN UNVERSIONED WEBSITE

# `make deploy` publishes a website on GitHub Pages *without* versioning.
# If the website is already deployed as versioned, it first needs to be
# *completely* cleared using `mike delete --all --push`.

# N.B. To prevent inadvertent overwriting of a previously-deployed *versioned*
# website, deploying an *unversioned* website requires `mike` to be installed.

.PHONY: deploy

ifndef VERSION
deploy:
	@if [[ -z "$$(mike list)" ]]; then \
	    NO_MKDOCS_2_WARNING=1 mkdocs gh-deploy --force --ignore-version; \
	else \
	    echo "Error: unversioned deployment blocked by deployed version(s)."; \
	    echo "To deploy an update to version ..., use 'make deploy VERSION=...'."; \
	    echo "To clear ALL deployed versions, use 'mike delete --all --push'."; \
	fi
endif

# The target `deploy` is defined differently when VERSION is set (see below).

# Note: `mkdocs gh-deploy --ignore-version` allows the version of `mkdocs`
# to differ from the previous deployment. It is unrelated to website versions.

##############################################################################
# REMOVE GENERATED FILES

# `make clean-all` removes generated files.

.PHONY: clean-all
clean-all: clean-html clean-md
	@rm -rf $(TEMP)
	@rm -rf $(SITE)

# To ensure that the generated website does not include outdated HTML pages
# for modules that were previously (but are no longer) imported by ROOT,
# the corresponding `*.html` files in HTML should be removed. If HTML=docs,
# it is difficult to distinguish such files from non-generated HTML files.
# To avoid the danger of removing files created by the user, it is left to
# the user to identify and delete outdated `*.html` files manually when
# HTML=docs. Similarly for the generated directories in MD when MD=docs.

# If docs/*.{html,md,css,js} files are all generated, uncomment the 
# rm command below.

.PHONY: clean-html
clean-html:
ifeq ($(HTML),docs)
	@echo "Warning: manually remove any obsolete docs/*.html files"
# 	@rm -f docs/*.{html,css,js}
else
	@rm -rf $(HTML)
endif

# If the subdirectories of docs that include index.md files are all generated,
# uncomment the rm command below.

.PHONY: clean-md
clean-md:
ifeq ($(MD),docs)
# 	@echo "Warning: manually remove any obsolete docs/**/*.md files"
	@find docs -name '*.md' \
	    ! -path 'docs/javascripts/*' ! -path 'docs/stylesheets/*' \
	    ! -path 'docs/Library/*' ! -path 'docs/README.md' ! -path 'docs/meta-notation.md' \
	    -delete
	@find docs -type d -empty -delete
else
	@rm -rf $(MD)
endif

##############################################################################
# MANAGE VERSIONED DEPLOYMENT

# N.B. The following commands use `mike` to push commits to the `gh-pages`
# branch, This starts a GitHub Action to deploy the updated website. If a
# new command is run before the action from the previous command has finished,
# the action may be aborted, causing a failed run. To avoid such issues,
# run a series of `mike` commands directly, including the `--push` option only
# in the last command.

# START VERSIONING

# `make start-versioning` clears a deployed *unversioned* site, in preparation
# for versioned deployment.
#
# To completely clear a *versioned* site, use `mike delete --all --push`.

# N.B. Before running `make start-versioning`, check that `mike` is installed,
# and uncomment the following lines in mkdocs.yml:
#
# extra:
#   version:
#     provider: mike

.PHONY: start-versioning
start-versioning:
ifndef VERSION
	@if [[ -z "$$(mike list)" ]]; then \
	    mike delete --all --allow-empty --push; \
	    echo "Cleared any deployed unversioned website"; \
	else \
	    echo "Error: blocked by currently deployed version(s)"; \
	    echo "To clear ALL deployed versions, use 'mike delete --all --push'"; \
	fi
else
	@echo "Error: superfluous VERSION argument; start-versioning abandoned"
endif

# DEPLOY A VERSION

# `make deploy VERSION=v` publishes version v of the website:

ifdef VERSION
deploy:
	@mike deploy $(VERSION) --push
	@echo "Deployed generated website as version $(VERSION)"
endif

# It is recommended to omit patch numbers in semantic versioning.
# Version identifiers that "look like" versions (e.g. 1.2.3, 1.0b1, v1.0)
# are treated as ordinary versions, whereas other identifiers, like devel,
# are treated as development versions, and placed above ordinary versions.

# SET A DEPLOYED VERSION AS DEFAULT

# `make default VERSION=...` sets a previously deployed version as the default,
# *without* deploying the current generated website. It also creates or updates
# the alias `default` to point to the default version.

.PHONY: default
default:
ifdef VERSION
	@mike alias $(VERSION) default --update-aliases
	@mike set-default $(VERSION) --allow-empty --push
	@echo "The default version is now $(VERSION)"
else
	@echo "Error: missing VERSION=..."
endif

# DELETE A DEPLOYED VERSION

# `make delete VERSION=...` removes a deployed version of a website.

# If VERSION is set as the default version, this can break existing links to
# the website! To avoid that, first use `make default VERSION=...` to change
# the default to a different version.

.PHONY: delete
delete:
ifdef VERSION
	@mike delete $(VERSION) --allow-empty --push
	@echo "Deleted deployed version $(VERSION)"
else
	@echo "Error: missing VERSION=..."
endif

# LIST VERSIONS

# `make list-versions` lists the current deployed versions.

.PHONY: list-versions
list-versions:
	@mike list

##############################################################################
# DEBUG

# `make debug` shows the values of some of the variables assigned in this file:

.PHONY: debug
export DEBUG
debug:
	@echo "$$DEBUG"

define DEBUG

PROJECT: $(PROJECT)
DIR:     $(DIR)
ROOT:    $(ROOT)
HTML:    $(HTML)
MD:      $(MD)

HTML-INDEX: $(HTML-INDEX)
MD-INDEX:   $(HTML-INDEX)

SITE:    $(SITE)
TEMP:    $(TEMP)
VERSION: $(VERSION)

DOCS2HTML: $(DOCS2HTML)
DOCS2MD:   $(DOCS2MD)
HTML2DOCS: $(HTML2DOCS)
MD2DOCS:   $(MD2DOCS)

HIDE-INDEXES: $(HIDE-INDEXES)

INCLUDE-PATHS: $(strip $(INCLUDE-PATHS))
ROOT-PATHS:    $(strip $(ROOT-PATHS))
ROOT-FILES:    $(strip $(ROOT-FILES))

endef

##############################################################################
# GENERATE PLAIN AGDA AND LATEX

PLAIN := plain

LATEX := latex

# For each *.lagda.md file, a *.lagda and a *.tex file are generated in LATEX

LAGDA-MD-FILES := \
	$(sort \
	  $(foreach d, $(INCLUDE-PATHS), \
	    $(shell find $d -name '*.lagda.md')))

PLAIN-FILES := $(addprefix $(PLAIN)/, $(patsubst %.lagda.md,%.agda, $(LAGDA-MD-FILES)))

LAGDA-FILES := $(addprefix $(LATEX)/, $(patsubst %.lagda.md,%.lagda, $(LAGDA-MD-FILES)))

LATEX-FILES := $(LAGDA-FILES:.lagda=.tex)

# `make gen-plain` generates PLAIN/DIR_1/*.agda files from *.lagda.md files

gen-plain: $(PLAIN-FILES)
	@echo "Generated .agda files in $(PLAIN)"

$(PLAIN-FILES): Makefile | $(PLAIN)

$(PLAIN):
	@mkdir $(PLAIN) && rm -rf $(PLAIN)/*

$(PLAIN)/%.agda: %.lagda.md
	@mkdir -p $(@D) && cp -f $< $@
#	Make start and end of code blocks easy to match:
	@sd '```agda' '%agda' $@
	@sd '```' '%/agda' $@
#	Remove pure prose:
	@sd '\A[^%]*\z' '' $@
#	Remove prose blocks:
	@sd '%/agda[^%]*%agda' '' $@
	@sd '\A[^%]*%agda\n' '' $@
	@sd '\n%/agda[^%]*\z' '' $@
#	Remove --"hide" and --"/hide" lines
	@sd -- '--"hide"\n' '' $@
	@sd '\n--"/hide"' '' $@

# `make gen-lagda` generates LATEX/DIR_1/*.lagda files from *.lagda.md files using pandoc

.PHONY: gen-lagda
gen-lagda: $(LAGDA-FILES)
	@echo "Generated .lagda files in $(LATEX)"

$(LAGDA-FILES): Makefile | $(LATEX)

$(LATEX):
	@mkdir $(LATEX) && rm -rf $(LATEX)/* && cp postprocess-latex.pl $(LATEX)

$(LATEX)/%.lagda: %.lagda.md
#	Use pandoc to transform Markdown to LaTeX, adjusting heading levels:
	@pandoc -f markdown -t latex --syntax-highlighting=none \
	    --shift-heading-level-by=$(words $(wordlist 2,10, $(subst /, , $(*D)))) \
	    -o $@ $<
#	Pandoc transforms ```agda...``` to a verbatim environment:
	@sd '\\begin\{verbatim\}' '\\begin{code}' $@
	@sd '\\end\{verbatim\}' '\\end{code}' $@
#	Pandoc transforms `...` to \texttt{...}:
	@sd '\\texttt\{' '\\AgdaRef{' $@
#	Pandoc doesn't support label prefixes:
	@sd '\\label\{' '\label{$(patsubst agda/%,%, $(*D)/$(*F))-' $@
#	Transform [(bibkey)] references to \cite{bibkey}:
	@sd '\\href\{https://[^\{\}]*\}\{\(([^ ()]*)\)\}' \
	    '\cite{$$1}' $@
#	Transform \cite{bibkey1}~...~\cite{bibkeyN} to \cite{bibkey1,...,bibkeyN}:
	@sd '\}~\\cite\{' ',' $@
#	Transform references to relative URLs to link to generated website:
#	[§ ...] -> Section~\ref{...} '||`
	@sd '\\href\{(\.\./)*([^:\{\}]*)/index\.md\\#([^\{\}]*)\}\{§ ([^\{\}]*)\}' \
	    'Section~\ref{$$2-$$3}\,\href{https://pdmosses.github.io/mfps2026-agda/$$2/\#$$3}{$$\Uparrow$$}' \
	    $@
	@sd '\\href\{(\.\./)*([^:\{\}]*)\.md\\#([^\{\}]*)\}\{§ ([^\{\}]*)\}' \
	    'Section~\ref{$$2-$$3}\,\href{https://pdmosses.github.io/mfps2026-agda/$$2/\#$$3}{$$\Uparrow$$}' \
	    $@
#	[...] -> ... (Section~\ref{...} '||`)
	@sd '\\href\{(\.\./)*([^:\{\}]*)/index\.md\\#([^\{\}]*)\}\{([^\{\}]*)\}' \
	    '$$4 (Section~\ref{$$2-$$3}\,\href{https://pdmosses.github.io/mfps2026-agda/$$2/\#$$3}{$$\Uparrow$$})' \
	    $@
	@sd '\\href\{(\.\./)*([^:\{\}]*)\.md\\#([^\{\}]*)\}\{([^\{\}]*)\}' \
	    '$$4 (Section~\ref{$$2-$$3}\,\href{https://pdmosses.github.io/mfps2026-agda/$$2/\#$$3}{$$\Uparrow$$})' \
	    $@
	@sd '\\begin\{code\}' "\\\\begin{AgdaSuppressSpace}\n\\\\begin{code}" $@
	@sd '\\end\{code\}' "\\\\end{code}\n\\\\end{AgdaSuppressSpace}" $@
#	Transform \n--"hide"\n...\n--"/hide"\n to a hidden code block
#	where ... does not contain ":
	@sd '\n--"hide"\n([^\"]*)\n--"/hide"\n' \
	    "\n\\\\end{code}\n\\\\begin{code}[hide]\n\$$1\n\\\\end{code}\n\\\\begin{code}\n" \
	    $@
#	Remove generated empty code blocks:
	@sd '\n\\begin\{code\}\n\\end\{code\}' '' $@
#	Comment-out blank lines around code blocks:
	@sd '\n\n\\begin\{AgdaSuppressSpace\}' "\n%\n\\\\begin{AgdaSuppressSpace}" $@
	@sd '\\end\{AgdaSuppressSpace\}\n\n' "\\\\end{AgdaSuppressSpace}\n%\n" $@
#	Delete @latex and @/latex:
	@sd '@[/]?latex' '' $@

LAGDA := agda $(addprefix --include-path=, $(addprefix $(LATEX)/, $(INCLUDE-PATHS)))

LAGDA-QUIET   := $(LAGDA) --trace-imports=0
LAGDA-VERBOSE := $(LAGDA) --trace-imports=3

# `make gen-latex` generates *.tex files from *.lagda files using agda and perl

.PHONY: gen-latex
gen-latex: $(LATEX-FILES)
	@echo "Generated .tex files in $(LATEX)"

$(LATEX-FILES): Makefile | $(LATEX)

$(LATEX)/%.tex: $(LATEX)/%.lagda
#	Use agda to transform *.lagda to *.tex:
	@$(LAGDA-QUIET) --latex --latex-dir=$(LATEX)/$(firstword $(INCLUDE-PATHS)) $<
#	Use postprocess-latex to fix arguments of \AgdaRef commands:
	@perl postprocess-latex.pl $@ > $@.processed
	@mv $@.processed $@

# `make clean-latex` removes all the files generated by gen-lagda and gen-latex

.PHONY: clean-latex
clean-latex:
	@rm -rf $(LATEX)/agda

.PHONY: debug-latex
export DEBUGLATEX
debug-latex:
	@echo "$$DEBUGLATEX"

define DEBUGLATEX

LAGDA: $(LAGDA)
LATEX: $(LATEX)

LAGDA-MD-FILES: $(strip $(LAGDA-MD-FILES))

PLAIN-FILES:    $(strip $(PLAIN-FILES))

LAGDA-FILES:    $(strip $(LAGDA-FILES))

LATEX-FILES:    $(strip $(LATEX-FILES))

endef