INHERIT: agda-pages/agda-pages.yml

site_name: XDS-Agda
site_url:  https://pdmosses.github.io/xds-agda/
repo_name: pdmosses/xds-agda
repo_url:  https://github.com/pdmosses/xds-agda

# To deploy website versions:
# - install mike (https://github.com/jimporter/mike/)
# - uncomment the following lines:
extra:
  version:
    provider: mike
