nav:
  - Lambda-Calculus:
    - md/LC/
  - Library:
    - md/Library/index.md
    - md/*
  - HTML: html/LC.index.html
  - PDF: pdf/LC.index.pdf

preserve_directory_names: true

sort:
  sections: mixed