nav:
  - About:
    - index.md
    - LC.md
    - PCF.md
    - Scm.md
    - meta-notation.md
  - Lambda-Calculus:
    - md/LC/index.md
    - md/LC/*
  - PCF:
    - md/PCF/index.md
    - md/PCF/*
  - Scm:
    - md/Scm/index.md
    # - md/Scm/Notation/index.md
    - md/Scm/*
  - Library:
    - Library/index.md
    - md/*
  
preserve_directory_names: true

sort:
  sections: mixed