nav:
  - About:
    - index.md
    - LC.md
    - PCF.md
  - Lambda-Calculus:
    - md/LC/index/index.md
    - md/LC/*
  - PCF:
    - md/PCF/index/index.md
    - md/PCF/*
  - Library:
    - Library/index.md
    - md/*
  # - HTML:
  #   - Lambda-Calculus: html/LC.index.html
  #   - PCF: html/PCF.index.html
  # - PDF:
  #   - Lambda-Calculus: pdf/LC.index.pdf
  #   - PCF: pdf/PCF.index.pdf

preserve_directory_names: true

sort:
  sections: mixed